apiVersion: v1
kind: Service
metadata:
    name: "verycoolapi-service"
    namespace: verycoolapi
    labels:
        app: "verycoolapi"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "verycoolapi"
